import 'dart:convert';

import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:dog_detection/dog_detection.dart';

/// Integration test that compares Flutter dog detection pipeline output
/// against Python reference data to ensure numerical equivalence.
///
/// Reference data generated by:
///   cd dogs-in-the-wild-ml && python scripts/dump_reference_data.py \
///       `<path>`/dachshund_test.jpg rtmpose
///
/// Tolerances account for:
/// - Python truncates SSD bbox to int; Flutter keeps as double
/// - Python expand_box uses int(bw*margin); Flutter uses double
/// - Minor float32/float16 rounding differences across TFLite runtimes
/// - OpenCV resize interpolation differences between Python PIL and opencv_dart
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  late Map<String, dynamic> refData;
  late DogDetector detector;
  late List<Dog> results;

  setUpAll(() async {
    // Load reference data from app assets
    final refJsonStr = await rootBundle.loadString(
      'integration_test/reference_data.json',
    );
    refData = jsonDecode(refJsonStr) as Map<String, dynamic>;

    // Load test image
    final imageData = await rootBundle.load(
      'packages/dog_detection/assets/samples/dachshund_test.jpg',
    );
    final imageBytes = imageData.buffer.asUint8List();

    // Initialize detector in full mode with RTMPose (matching Python reference)
    detector = DogDetector(
      mode: DogDetectionMode.full,
      poseModel: AnimalPoseModel.rtmpose,
      landmarkModel: DogLandmarkModel.full,
      cropMargin: 0.20,
      detThreshold: 0.5,
    );
    await detector.initialize();

    // Run detection
    results = await detector.detect(imageBytes);
  });

  tearDownAll(() async {
    await detector.dispose();
  });

  group('Pipeline equivalence with Python', () {
    test('detects exactly 1 dog', () {
      final refDogs = refData['dogs'] as List;
      expect(results.length, equals(refDogs.length),
          reason: 'Number of detected dogs should match Python');
      expect(results.length, equals(1));
    });

    test('SSD detection score matches', () {
      final refDog = (refData['dogs'] as List)[0] as Map<String, dynamic>;
      final refScore = (refDog['det_score'] as num).toDouble();

      // Score should be very close (both > 0.999)
      expect(results[0].score, greaterThan(0.99),
          reason: 'Detection score should be > 0.99');
      expect((results[0].score - refScore).abs(), lessThan(0.01),
          reason: 'Detection score should match Python within 0.01');
    });

    test('SSD bounding box matches within tolerance', () {
      final refDog = (refData['dogs'] as List)[0] as Map<String, dynamic>;
      final refBbox = (refDog['det_bbox'] as List).cast<num>();

      // Python truncates to int, Flutter keeps double. Allow 5px tolerance.
      const bboxTolerance = 5.0;
      final bbox = results[0].boundingBox;

      _expectClose(
          bbox.left, refBbox[0].toDouble(), bboxTolerance, 'bbox.left');
      _expectClose(bbox.top, refBbox[1].toDouble(), bboxTolerance, 'bbox.top');
      _expectClose(
          bbox.right, refBbox[2].toDouble(), bboxTolerance, 'bbox.right');
      _expectClose(
          bbox.bottom, refBbox[3].toDouble(), bboxTolerance, 'bbox.bottom');
    });

    test('species classification matches', () {
      final refDog = (refData['dogs'] as List)[0] as Map<String, dynamic>;
      final refSpecies = refDog['species'] as String;

      expect(results[0].species, equals(refSpecies),
          reason: 'Species should match Python ("dog")');
    });

    test('species confidence is reasonable', () {
      final refDog = (refData['dogs'] as List)[0] as Map<String, dynamic>;
      final refConf = (refDog['species_confidence'] as num).toDouble();

      expect(results[0].speciesConfidence, isNotNull);
      // Confidence should be in same ballpark (within 10% absolute)
      // Confidence values can differ significantly between TF and TFLite
      // runtimes due to float16 quantization and different resize interpolation.
      // The important thing is that the species label is correct.
      expect(
        (results[0].speciesConfidence! - refConf).abs(),
        lessThan(0.30),
        reason: 'Species confidence should match Python within 0.30. '
            'Got ${results[0].speciesConfidence}, expected $refConf',
      );
    });

    test('body pose has 24 keypoints', () {
      expect(results[0].pose, isNotNull, reason: 'Pose should not be null');
      expect(results[0].pose!.landmarks.length, equals(24),
          reason: 'Should have 24 body keypoints (indices 15-38)');
    });

    test('body pose keypoints match within tolerance', () {
      final refDog = (refData['dogs'] as List)[0] as Map<String, dynamic>;
      final refKps =
          (refDog['body_keypoints'] as List).cast<Map<String, dynamic>>();

      final pose = results[0].pose!;

      // Body keypoints should be within 50px of Python reference.
      // Tolerance accounts for:
      // - Python expand_box uses int(bw*margin), Flutter uses double
      // - OpenCV resize vs PIL resize interpolation at letterbox step
      // - Float16 model produces different activations across runtimes
      // - Small differences cascade through multi-stage pipeline
      const kpTolerance = 50.0;

      for (int i = 0; i < refKps.length; i++) {
        final refKp = refKps[i];
        final refX = (refKp['x'] as num).toDouble();
        final refY = (refKp['y'] as num).toDouble();
        final dartKp = pose.landmarks[i];

        _expectClose(
            dartKp.x, refX, kpTolerance, 'body_kp[${refKp['name']}].x');
        _expectClose(
            dartKp.y, refY, kpTolerance, 'body_kp[${refKp['name']}].y');
      }
    });

    test('face is detected', () {
      expect(results[0].face, isNotNull,
          reason: 'Face should be detected in full mode');
    });

    test('face bounding box matches within tolerance', () {
      final refDog = (refData['dogs'] as List)[0] as Map<String, dynamic>;
      final refFaceBbox = (refDog['face_bbox'] as List).cast<num>();

      final faceBbox = results[0].face!.boundingBox;

      // Face bbox tolerance is larger because:
      // - Face localizer runs on the expanded dog crop
      // - Different crop pixel boundaries from int vs double expand_box
      // - Letterbox resize differences
      const faceBboxTolerance = 25.0;

      _expectClose(faceBbox.left, refFaceBbox[0].toDouble(), faceBboxTolerance,
          'face_bbox.left');
      _expectClose(faceBbox.top, refFaceBbox[1].toDouble(), faceBboxTolerance,
          'face_bbox.top');
      _expectClose(faceBbox.right, refFaceBbox[2].toDouble(), faceBboxTolerance,
          'face_bbox.right');
      _expectClose(faceBbox.bottom, refFaceBbox[3].toDouble(),
          faceBboxTolerance, 'face_bbox.bottom');
    });

    test('face has 46 landmarks', () {
      expect(results[0].face!.hasLandmarks, isTrue);
      expect(results[0].face!.landmarks.length, equals(46),
          reason: 'Should have 46 face landmarks');
    });

    test('face landmarks match within tolerance', () {
      final refDog = (refData['dogs'] as List)[0] as Map<String, dynamic>;
      final refLms =
          (refDog['face_landmarks'] as List).cast<Map<String, dynamic>>();

      final faceLms = results[0].face!.landmarks;

      // Face landmarks have larger tolerance because the full pipeline
      // chains multiple models (SSD → face localizer → landmark model),
      // each adding small differences. Also, the Flutter pipeline uses
      // the single 384px model (DogLandmarkModel.full), while the Python
      // reference uses the 3-model ensemble. So we expect larger differences
      // here and just verify they're in the right ballpark.
      const faceLmTolerance = 40.0;

      for (int i = 0; i < refLms.length && i < faceLms.length; i++) {
        final refLm = refLms[i];
        final refX = (refLm['x'] as num).toDouble();
        final refY = (refLm['y'] as num).toDouble();
        final dartLm = faceLms[i];

        _expectClose(dartLm.x, refX, faceLmTolerance, 'face_lm[$i].x');
        _expectClose(dartLm.y, refY, faceLmTolerance, 'face_lm[$i].y');
      }
    });

    test('AnimalPoseLandmarkType enum indices match Python keypoint indices',
        () {
      // Verify the enum ordering matches the Python keypoint name mapping
      expect(
          AnimalPoseLandmarkType.neckBase.index, equals(0)); // Python index 15
      expect(
          AnimalPoseLandmarkType.neckEnd.index, equals(1)); // Python index 16
      expect(AnimalPoseLandmarkType.throatBase.index, equals(2)); // 17
      expect(AnimalPoseLandmarkType.throatEnd.index, equals(3)); // 18
      expect(AnimalPoseLandmarkType.backBase.index, equals(4)); // 19
      expect(AnimalPoseLandmarkType.backEnd.index, equals(5)); // 20
      expect(AnimalPoseLandmarkType.backMiddle.index, equals(6)); // 21
      expect(AnimalPoseLandmarkType.tailBase.index, equals(7)); // 22
      expect(AnimalPoseLandmarkType.tailEnd.index, equals(8)); // 23
      expect(AnimalPoseLandmarkType.frontLeftThigh.index, equals(9)); // 24
      expect(AnimalPoseLandmarkType.frontLeftKnee.index, equals(10)); // 25
      expect(AnimalPoseLandmarkType.frontLeftPaw.index, equals(11)); // 26
      expect(AnimalPoseLandmarkType.frontRightThigh.index, equals(12)); // 27
      expect(AnimalPoseLandmarkType.frontRightKnee.index, equals(13)); // 28
      expect(AnimalPoseLandmarkType.frontRightPaw.index, equals(14)); // 29
      expect(AnimalPoseLandmarkType.backLeftPaw.index, equals(15)); // 30
      expect(AnimalPoseLandmarkType.backLeftThigh.index, equals(16)); // 31
      expect(AnimalPoseLandmarkType.backRightThigh.index, equals(17)); // 32
      expect(AnimalPoseLandmarkType.backLeftKnee.index, equals(18)); // 33
      expect(AnimalPoseLandmarkType.backRightKnee.index, equals(19)); // 34
      expect(AnimalPoseLandmarkType.backRightPaw.index, equals(20)); // 35
      expect(AnimalPoseLandmarkType.bellyBottom.index, equals(21)); // 36
      expect(AnimalPoseLandmarkType.bodyMiddleRight.index, equals(22)); // 37
      expect(AnimalPoseLandmarkType.bodyMiddleLeft.index, equals(23)); // 38
    });
  });

  group('Pipeline sanity checks', () {
    test('image dimensions are correct', () {
      final refSize = (refData['image_size'] as List).cast<int>();
      expect(results[0].imageWidth, equals(refSize[0]));
      expect(results[0].imageHeight, equals(refSize[1]));
    });

    test('detection score is high', () {
      expect(results[0].score, greaterThan(0.99));
    });

    test('body keypoints are within image bounds', () {
      final w = results[0].imageWidth.toDouble();
      final h = results[0].imageHeight.toDouble();
      for (final lm in results[0].pose!.landmarks) {
        expect(lm.x, greaterThanOrEqualTo(-50),
            reason: '${lm.type.name}.x should be >= -50');
        expect(lm.x, lessThanOrEqualTo(w + 50),
            reason: '${lm.type.name}.x should be <= width+50');
        expect(lm.y, greaterThanOrEqualTo(-50),
            reason: '${lm.type.name}.y should be >= -50');
        expect(lm.y, lessThanOrEqualTo(h + 50),
            reason: '${lm.type.name}.y should be <= height+50');
      }
    });

    test('face landmarks are within image bounds', () {
      final w = results[0].imageWidth.toDouble();
      final h = results[0].imageHeight.toDouble();
      for (final lm in results[0].face!.landmarks) {
        expect(lm.x, greaterThanOrEqualTo(-50),
            reason: '${lm.type.name}.x should be >= -50');
        expect(lm.x, lessThanOrEqualTo(w + 50),
            reason: '${lm.type.name}.x should be <= width+50');
        expect(lm.y, greaterThanOrEqualTo(-50),
            reason: '${lm.type.name}.y should be >= -50');
        expect(lm.y, lessThanOrEqualTo(h + 50),
            reason: '${lm.type.name}.y should be <= height+50');
      }
    });

    test('Dog.toMap() and Dog.fromMap() roundtrip', () {
      final dog = results[0];
      final map = dog.toMap();
      final restored = Dog.fromMap(map);

      expect(restored.score, equals(dog.score));
      expect(restored.species, equals(dog.species));
      expect(restored.imageWidth, equals(dog.imageWidth));
      expect(restored.imageHeight, equals(dog.imageHeight));
      expect(restored.boundingBox.left, equals(dog.boundingBox.left));
      expect(
          restored.pose?.landmarks.length, equals(dog.pose?.landmarks.length));
      expect(
          restored.face?.landmarks.length, equals(dog.face?.landmarks.length));
    });
  });
}

/// Asserts that [actual] is within [tolerance] of [expected].
void _expectClose(
    double actual, double expected, double tolerance, String label) {
  final diff = (actual - expected).abs();
  expect(diff, lessThanOrEqualTo(tolerance),
      reason: '$label: expected $expected, got $actual (diff=$diff, '
          'tolerance=$tolerance)');
}
